# -*- coding: utf-8 -*-
"""민감도 조정 모델 최종

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zV-XV8gQq-IvLFzlmUBltPzKEuh0yqiy
"""

import pandas as pd
import numpy as np

# 1) 데이터 로드
df = pd.read_csv("modeling_data_generated_large.csv")

# 2) 점수 계산 (FanLevel 내 FalseAlarm 정규화)
EPS = 1e-9
ALPHA = 3.0
BETA  = 1.0

def add_score(_df):
    fa_min = _df.groupby("FanLevel")["FalseAlarm"].transform("min")
    fa_max = _df.groupby("FanLevel")["FalseAlarm"].transform("max")
    fa_norm = (_df["FalseAlarm"] - fa_min) / (fa_max - fa_min + EPS)
    out = _df.copy()
    out["FA_Norm"] = fa_norm.clip(0,1)
    out["Score"]   = ALPHA * out["TrueDetectionRate"] - BETA * out["FA_Norm"]
    return out

df_scored = add_score(df)

# 3) FanLevel별 최적 민감도 계산
def pick_best(g):
    return g.sort_values(
        ["Score","FA_Norm","TrueDetectionRate","SensorSensitivity"],
        ascending=[False, True, False, True]
    ).iloc[0]

best = (df_scored.groupby("FanLevel", as_index=False)
                  .apply(pick_best)
                  .reset_index(drop=True))

summary = best[["FanLevel","SensorSensitivity","TrueDetectionRate","FalseAlarm","Score"]].copy()
summary.rename(columns={"SensorSensitivity":"OptimalSensitivity"}, inplace=True)
summary["TrueDetectionRate"] = summary["TrueDetectionRate"].round(3)
summary["FalseAlarm"] = summary["FalseAlarm"].round(1)
summary["Score"] = summary["Score"].round(6)

# 4) 결과 출력
print(summary.to_string(index=False))

# 전체 데이터에 라벨 부착해 저장
best_map = dict(zip(best["FanLevel"], best["SensorSensitivity"]))
df_labeled = df_scored.copy()
df_labeled["OptimalSensitivity"] = df_labeled["FanLevel"].map(best_map).astype(int)
df_labeled.to_csv("model_labeled_dataset.csv", index=False)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

# 1) 데이터 로드
df = pd.read_csv("model_labeled_dataset.csv")

# 2) Feature/Target
X = df[["FanLevel"]]                      # 현재 단계: FanLevel만 사용
y = df["OptimalSensitivity"].astype(int)

# 3) 학습/검증 분리
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 4) RF 학습
clf = RandomForestClassifier(
    n_estimators=400,
    max_depth=None,
    min_samples_split=4,
    random_state=42,
    n_jobs=-1
)
clf.fit(X_train, y_train)

# 5) 평가
y_pred = clf.predict(X_test)
print("Accuracy:", round(accuracy_score(y_test, y_pred), 4))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, zero_division=0))

# 6) 예측 예시
print(clf.predict(pd.DataFrame({"FanLevel":[0,1,2,3]})))

# Random case
import pandas as pd
import numpy as np

# 입력
IN_EXPANDED = "score_expanded_operational.csv"
OUT_LABELS  = "score_labels_simple.csv"

# 1) 로드
expanded = pd.read_csv(IN_EXPANDED)

# 2) Score = 3*TD - 1*FA_Norm  (RowID 내 정규화)
EPS = 1e-9
expanded["FA_min"] = expanded.groupby("RowID")["FalseAlarms_25s_s"].transform("min")
expanded["FA_max"] = expanded.groupby("RowID")["FalseAlarms_25s_s"].transform("max")
expanded["FA_Norm"] = ((expanded["FalseAlarms_25s_s"] - expanded["FA_min"]) /
                       (expanded["FA_max"] - expanded["FA_min"] + EPS)).clip(0, 1)

expanded["Score"] = 3.0 * expanded["TrueDetectionRate_s"] - 1.0 * expanded["FA_Norm"]

# 3) 환경(RowID)별 최적 민감도 선택
def pick_best(g):
    return g.sort_values(
        ["Score", "FA_Norm", "TrueDetectionRate_s", "Sensitivity"],
        ascending=[False, True, False, True]
    ).iloc[0]

best = (expanded.groupby("RowID", as_index=False)
                  .apply(pick_best)
                  .reset_index(drop=True))

# 4) 결과 정리/저장
labels = best[[
    "RowID","ZoneID","WindSpeed_kn","WindDirection","Season","Weather","Distance_m",
    "Sensitivity","TrueDetectionRate_s","FalseAlarms_25s_s","FA_Norm","Score"
]].rename(columns={
    "Sensitivity":"OptimalSensitivity",
    "TrueDetectionRate_s":"TDR_at_Optimal",
    "FalseAlarms_25s_s":"FA_at_Optimal"
})

labels.to_csv(OUT_LABELS, index=False)

print("saved:", OUT_LABELS, "rows:", len(labels))
print("distribution:", labels["OptimalSensitivity"].value_counts().sort_index().to_dict())
print(labels.head(10).to_string(index=False))# train_rf_optimal_sensitivity.py
import pandas as pd
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, top_k_accuracy_score
from sklearn.ensemble import RandomForestClassifier
import joblib

# ===== 경로 =====
LABELS_CSV = "score_labels_simple.csv"   # <- score_expanded_with_sensitivity에서 3:1로 라벨링한 결과
MODEL_OUT  = "rf_pipeline_optimal_sensitivity.joblib"

# ===== 데이터 로드 =====
df = pd.read_csv(LABELS_CSV)

# ===== 피처/타깃 정의 =====
FEATURES_CAT = ["ZoneID", "WindDirection", "Season", "Weather"]
FEATURES_NUM = ["WindSpeed_kn", "Distance_m"]
TARGET = "OptimalSensitivity"

# 누락 제거 및 타입 보정
df = df.dropna(subset=FEATURES_CAT + FEATURES_NUM + [TARGET]).copy()
df[TARGET] = df[TARGET].astype(int)

X = df[FEATURES_CAT + FEATURES_NUM]
y = df[TARGET]

# ===== 전처리+모델 파이프라인 =====
ct = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), FEATURES_CAT),
        ("num", "passthrough", FEATURES_NUM),
    ]
)
rf = RandomForestClassifier(
    n_estimators=500,
    max_depth=None,
    min_samples_split=4,
    random_state=42,
    n_jobs=-1
)
pipe = Pipeline([("prep", ct), ("rf", rf)])

# ===== 학습/검증 분리 & 학습 =====
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
pipe.fit(X_train, y_train)

# ===== 평가 =====
y_pred = pipe.predict(X_test)
proba  = pipe.predict_proba(X_test)
classes_ = pipe.named_steps["rf"].classes_

print("Accuracy:", round(accuracy_score(y_test, y_pred), 4))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, zero_division=0))

# top-2 accuracy (두 후보 안에 정답이 포함될 확률)
print("Top-2 Accuracy:", round(top_k_accuracy_score(y_test, proba, k=2, labels=classes_), 4))

# 가벼운 교차검증(3-fold)
cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
cv_scores = cross_val_score(pipe, X, y, cv=cv, scoring="accuracy", n_jobs=-1)
print("CV(3-fold) Acc:", [round(s,4) for s in cv_scores], "-> mean:", round(cv_scores.mean(),4))

# ===== 저장 =====
joblib.dump(pipe, MODEL_OUT)
print("Saved model to:", MODEL_OUT)