# -*- coding: utf-8 -*-
"""이상+노후화 탐지 모델 최종

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5QyoxNMCm292oqeG_rP1ECEXIXdlGO2
"""

import numpy as np, pandas as pd
from datetime import datetime, timedelta
import os, json
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, callbacks

# ----------------------------- 1) 데이터 생성 -----------------------------
rng = np.random.default_rng(123)
devices = ["D_normal", "D_aging", "D_anom"]
weathers = ["맑음","구름","비","눈"]
dirs_all = ["N","NE","E","SE","S","SW","W","NW"]
seasons_all = ["봄","여름","가을","겨울"]
season_map = {"봄": 0, "여름": 1, "가을": 2, "겨울": 3}

start = datetime(2025, 8, 25, 0, 0, 0)
steps = 7*48  # 7일 × 30분 간격
timestamps = [start + timedelta(minutes=30*i) for i in range(steps)]

rows = []
for d in devices:
    wind = rng.gamma(3.0, 2.0, size=steps)
    sens = rng.integers(1, 10, size=steps)
    dirs = rng.choice(dirs_all, size=steps)
    season = rng.choice(seasons_all, size=steps)
    weather = rng.choice(weathers, size=steps)

    base = 0.22 * wind + 0.55 * (sens/9) + 0.12 * (np.isin(dirs, ["NE","E","SE"]).astype(float))
    base += np.choose([["맑음","구름","비","눈"].index(w) for w in weather], [0.0, 0.1, 0.35, 0.2])
    base += np.choose([season_map[s] for s in season], [0.0, 0.2, 0.1, 0.15])

    if d == "D_normal":
        base2 = base
    elif d == "D_aging":
        drift = np.linspace(0.0, 1.5, steps)  # 노후화로 점진적 증가
        base2 = base + drift
    else:  # D_anom
        base2 = base.copy()
        spikes = rng.choice([0,1], p=[0.9,0.1], size=steps)
        for i in range(steps):
            if spikes[i] == 1:
                factor = rng.choice([0.25, 3.0])
                base2[i] *= factor

    popup = np.maximum(0, (base2 * 8.5) + rng.normal(0, 1.2, size=steps)).round().astype(int)

    for t in range(steps):
        rows.append({
            "Timestamp": timestamps[t].isoformat(),
            "DeviceID": d,
            "ZoneID": 1,
            "Weather": weather[t],
            "WindSpeed_kn": round(float(wind[t]), 2),
            "WindDirection": dirs[t],
            "Season": season[t],
            "Sensitivity": int(sens[t]),
            "PopupCount": int(popup[t]),
        })

df_all = pd.DataFrame(rows)

# ----------------------------- 1) 학습-----------------------------
train_cutoff = timestamps[3*48 - 1]
train_df = df_all[pd.to_datetime(df_all["Timestamp"]) <= train_cutoff].copy()
test_df = df_all.copy()

ID_COLS   = ["DeviceID"]
CAT_COLS  = ["Weather", "WindDirection", "Season"]
NUM_COLS  = ["WindSpeed_kn", "Sensitivity"]
TARGET_COL = "PopupCount"
THRESH_PCTL = 99.0
RANDOM_SEED = 7

def build_env_preprocessor(cat_cols, num_cols):
    cat_pipe = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("ohe", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
    ])
    num_pipe = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="mean")),
        ("scaler", StandardScaler()),
    ])
    return ColumnTransformer([
        ("cat", cat_pipe, cat_cols),
        ("num", num_pipe, num_cols),
    ], remainder="drop")

def build_env_baseline_model():
    return RandomForestRegressor(
        n_estimators=300, min_samples_split=4, random_state=RANDOM_SEED, n_jobs=-1
    )

def build_autoencoder(input_dim: int) -> keras.Model:
    enc_inputs = keras.Input(shape=(input_dim,), name="ae_input")
    x = layers.Dense(128, activation="relu")(enc_inputs)
    x = layers.BatchNormalization()(x)
    x = layers.Dense(64, activation="relu")(x)
    x = layers.BatchNormalization()(x)
    bottleneck = layers.Dense(16, activation="relu", name="bottleneck")(x)
    x = layers.Dense(64, activation="relu")(bottleneck)
    x = layers.BatchNormalization()(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.BatchNormalization()(x)
    dec_outputs = layers.Dense(input_dim, activation=None, name="ae_output")(x)
    ae = keras.Model(enc_inputs, dec_outputs, name="autoencoder")
    ae.compile(optimizer=keras.optimizers.Adam(1e-3), loss="mse")
    return ae

def reconstruction_error(x_true: np.ndarray, x_pred: np.ndarray) -> np.ndarray:
    return np.mean((x_true - x_pred) ** 2, axis=1)

pre = build_env_preprocessor(CAT_COLS, NUM_COLS)
env_model = build_env_baseline_model()
env_pipe = Pipeline([("pre", pre), ("rf", env_model)])

X_train = train_df[CAT_COLS + NUM_COLS]
y_train = train_df[TARGET_COL].values
env_pipe.fit(X_train, y_train)

X_train_pre = env_pipe.named_steps["pre"].transform(X_train)
r_train = (y_train - env_pipe.predict(X_train)).reshape(-1, 1)
ae_train = np.hstack([X_train_pre, r_train])

input_dim = ae_train.shape[1]
ae = build_autoencoder(input_dim)

tr_idx, va_idx = train_test_split(np.arange(ae_train.shape[0]), test_size=0.2, random_state=RANDOM_SEED, shuffle=True)
cbs = [
    callbacks.EarlyStopping(patience=8, restore_best_weights=True, monitor="val_loss"),
    callbacks.ReduceLROnPlateau(patience=4, factor=0.5, min_lr=1e-5)
]
ae.fit(ae_train[tr_idx], ae_train[tr_idx],
       epochs=120, batch_size=256, validation_data=(ae_train[va_idx], ae_train[va_idx]),
       callbacks=cbs, verbose=0)

pred_tr = ae.predict(ae_train, verbose=0)
err_tr = reconstruction_error(ae_train, pred_tr)
base_thresh = float(np.percentile(err_tr, THRESH_PCTL))

# ----------------------------- 2) 시퀀스 추론(EWMA/CUSUM) -----------------------------
EWMA_ALPHA = 0.2
CUSUM_K = 0.5
CUSUM_H = 5.0

def update_ewma(prev, x, alpha=EWMA_ALPHA):
    if prev is None:
        return float(x)
    return float(alpha * x + (1 - alpha) * prev)

def update_cusum(prev_pos, prev_neg, x, k=CUSUM_K, h=CUSUM_H):
    s_pos = max(0.0, prev_pos + (x - k))
    s_neg = max(0.0, prev_neg + (-x - k))
    alarm = (s_pos > h) or (s_neg > h)
    return s_pos, s_neg, alarm

test_df = test_df.sort_values("Timestamp").reset_index(drop=True)
states = {}
records = []

for _, row in test_df.iterrows():
    X_row = pd.DataFrame([row[CAT_COLS + NUM_COLS]])
    y = float(row[TARGET_COL])

    yhat = float(env_pipe.predict(X_row)[0])
    r = y - yhat

    X_pre = env_pipe.named_steps["pre"].transform(X_row)
    ae_in = np.hstack([X_pre, np.array([[r]])])
    ae_out = ae.predict(ae_in, verbose=0)
    err = float(reconstruction_error(ae_in, ae_out)[0])

    dev = row["DeviceID"]
    st = states.get(dev, {"ewma": None, "cusum_pos": 0.0, "cusum_neg": 0.0, "buf": []})

    buf = st["buf"]
    buf.append(err)
    if len(buf) > 50:
        buf.pop(0)
    buf_mean = float(np.mean(buf))
    buf_std = float(np.std(buf) + 1e-9)
    x_std = (err - buf_mean) / buf_std

    ewma_new = update_ewma(st["ewma"], err)
    s_pos, s_neg, cusum_alarm = update_cusum(st["cusum_pos"], st["cusum_neg"], x_std)

    dyn_thresh = base_thresh + 0.5 * max(0.0, ewma_new - base_thresh)
    is_anom = int((err > dyn_thresh) or cusum_alarm)

    records.append({
        "Timestamp": row["Timestamp"],
        "DeviceID": dev,
        "PopupCount": y,
        "yhat_env": yhat,
        "Residual": r,
        "ReconErr": err,
        "EWMA": ewma_new,
        "DynThreshold": dyn_thresh,
        "BaseThreshold": base_thresh,
        "CUSUM_pos": s_pos,
        "CUSUM_neg": s_neg,
        "CUSUM_Alarm": int(cusum_alarm),
        "IsAnomaly": is_anom,
    })

    states[dev] = {"ewma": ewma_new, "cusum_pos": s_pos, "cusum_neg": s_neg, "buf": buf}

res = pd.DataFrame(records)

# ----------------------------- 3) 저장 + 그래프 -----------------------------
os.makedirs("/mnt/data", exist_ok=True)
out_path = "/mnt/data/longrun_results.csv"
res.to_csv(out_path, index=False)

def plot_device(df, device_id):
    sub = df[df["DeviceID"] == device_id].copy()
    sub["Timestamp"] = pd.to_datetime(sub["Timestamp"])

    plt.figure(figsize=(12, 4))
    plt.plot(sub["Timestamp"], sub["ReconErr"], label="ReconErr")
    plt.plot(sub["Timestamp"], sub["DynThreshold"], label="DynThreshold")
    plt.plot(sub["Timestamp"], sub["BaseThreshold"], label="BaseThreshold")

    anom = sub[sub["IsAnomaly"] == 1]
    if len(anom) > 0:
        plt.scatter(anom["Timestamp"], anom["ReconErr"], label="Anomaly", s=10)

    plt.title(f"Device {device_id}: Recon Error vs Thresholds")
    plt.xlabel("Time")
    plt.ylabel("Value")
    plt.legend()
    plt.tight_layout()
    plt.show()

for d in devices:
    plot_device(res, d)

# 미리보기 10 행
print(res.head(10).to_string(index=False))
print("Saved results to:", out_path)